
[functions.line-login]
enabled = true
verify_jwt = true
import_map = "./functions/line-login/deno.json"
entrypoint = "./functions/line-login/index.ts"

[functions.line-login-v2]
enabled = true
verify_jwt = true
import_map = "./functions/line-login-v2/deno.json"
entrypoint = "./functions/line-login-v2/index.ts"

[functions.switch-menu]
enabled = true
verify_jwt = true
import_map = "./functions/switch-menu/deno.json"
entrypoint = "./functions/switch-menu/index.ts"
